### ISSUE TITLE
 the question about the  performance in  pantheon

### ISSUE THREAD

**Issue by jialianchen** [PCCproject/PCC-RL#17] opened 2021-07-26 04:00 UTC
hello ,i want to test the Auraro performance in  pantheon,but i meet some question when i use local model.
this is my pantheon_report
[pantheon_report.pdf](https://github.com/PCCproject/PCC-RL/files/6875434/pantheon_report.pdf)
i have the same question with  https://github.com/PCCproject/PCC-RL/issues/12 and https://github.com/PCCproject/PCC-RL/issues/16 when i use one machine,
but when i test the remote model ,it seems work well.
[pantheon_report.pdf](https://github.com/PCCproject/PCC-RL/files/6875457/pantheon_report.pdf)
i wonder whether you could give me some advice .
thanks for your help!

**Comment by r02b** [comment] 2021-08-23 16:35
Hey,

This seem to be a dupe of #12 and #16, so I'm going to close it. It seems it's more of a bootstrapping issue rather than an bug, and using two machines does solve the problem.

**Closed as completed by r02b** 2021-08-23 16:35 UTC
